steps:
  build:
    name: Build React App
    image: node:18
    commands:
      - npm ci
      - npm run build
    when:
      event: [push, pull_request]

  test:
    name: Run Tests
    image: node:18
    commands:
      - npm ci
      - npm test -- --watchAll=false --passWithNoTests
    when:
      event: [push, pull_request]

  lint:
    name: Code Linting
    image: node:18
    commands:
      - npm ci
      - npm run eslint
    when:
      event: [push, pull_request]

  deploy:
    name: Deploy to Production
    image: alpine
    commands:
      - echo "🚀 Deploying to production..."
      - echo "This is where you would add your deployment commands"
    when:
      branch: main
      event: push
