steps:
  build:
    name: Build React App
    image: node:18
    environment:
      # Skip Puppeteer Chromium download in CI to avoid disk space issues
      PUPPETEER_SKIP_DOWNLOAD: "true"
    commands:
      - npm ci --legacy-peer-deps
      - npm run build
    when:
      event: [push, pull_request]

  test:
    name: Run Tests
    image: node:18
    environment:
      PUPPETEER_SKIP_DOWNLOAD: "true"
    commands:
      - npm ci --legacy-peer-deps
      - npm test -- --watchAll=false --passWithNoTests
    when:
      event: [push, pull_request]

  lint:
    name: Code Linting
    image: node:18
    commands:
      - npm ci --legacy-peer-deps
      - npm run eslint
    when:
      event: [push, pull_request]

  deploy:
    name: Deploy to Production
    image: alpine
    commands:
      - echo "🚀 Deploying to production..."
      - echo "Add your deployment commands here"
    when:
      branch: main
      event: push
