steps:
  install:
    name: Install Dependencies
    image: node:18
    environment:
      PUPPETEER_SKIP_DOWNLOAD: "true"
    caches:
      - node
      - npm
    commands:
      - npm ci --legacy-peer-deps

  build:
    image: node:18
    commands:
      - npm run build
    depends_on:
      - install

  test:
    image: node:18
    commands:
      - npm test -- --watchAll=false --passWithNoTests
    depends_on:
      - install

  lint:
    image: node:18
    commands:
      - npm run eslint
    depends_on:
      - install

  deploy:
    image: alpine
    commands:
      - echo "🚀 Deploying to production..."
    when:
      branch: main
      event: push
